# Generated by Django 5.0.7 on 2024-07-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animes",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("genres", models.CharField(blank=True, max_length=100, null=True)),
                ("media", models.CharField(blank=True, max_length=10, null=True)),
                ("episodes", models.IntegerField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("members", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("season", models.CharField(blank=True, max_length=30, null=True)),
                ("source", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "animes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AnimeTest",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("genres", models.CharField(blank=True, max_length=100, null=True)),
                ("media", models.CharField(blank=True, max_length=10, null=True)),
                ("episodes", models.IntegerField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("members", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("season", models.CharField(blank=True, max_length=20, null=True)),
                ("source", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "anime_test",
                "managed": False,
            },
        ),
    ]
